[package]
name = "ferrite-core"
version.workspace = true
edition.workspace = true
description = "Core functionality for Ferrite image viewer"
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/ferrite-core"
readme = "README.md"
keywords = ["ferrite"]
categories = ["development-tools::debugging"]

[dependencies]
eframe.workspace = true
egui.workspace = true
image.workspace = true
rayon.workspace = true
tracing.workspace = true
ferrite-config = { version = "^0.1.1", path = "../ferrite-config" }
ferrite-logging = { version = "^0.1.1", path = "../ferrite-logging" }
